// Tarot Deck (78 cards) - Upright meanings only
// can also add "img": "images/cardname.jpg" later

const fullDeck = [
  { name: "The Fool", meaning: "beginnings, freedom, innocence, originality, adventure, idealism, spontaneity" },
  { name: "The Magician", meaning: "willpower, desire, being resourceful,, skill, ability, concentration, manifestation" },
  { name: "The High Priestess", meaning: "unconscious, intuition, mystery, spirituality, higher power, inner voice" },
  { name: "The Empress", meaning: "divine feminine, sensuality, fertility, nurturing, creativity, beauty, abundance, nature" },
  { name: "The Emperor", meaning: "stability, structure, protection, authority, control, practicality, focus, discipline" },
  { name: "The Hierophant", meaning: "tradition, social groups, conventionality, conformity, education, knowledge, beliefs" },
  { name: "The Lovers", meaning: "love, unions, partnerships, relationships, choices, romance, balance, unity" },
  { name: "The Chariot", meaning: "success, ambition, determination, willpower, control, self-discipline, focus" },
  { name: "Strength", meaning: "courage, bravery, confidence, compassion, self-confidence, inner power" },
  { name: "The Hermit", meaning: "self-reflection, introspection, contemplation, withdrawal, solitude, search for self" },
  { name: "Wheel of Fortune", meaning: "change, cycles, fate, decisive moments, luck, fortune, unexpected events" },
  { name: "Justice", meaning: "justice, karma, consequence, accountability, law, truth, honesty, integrity, cause and effect" },
  { name: "The Hanged Man", meaning: "sacrifice, waiting, uncertainty, lack of direction, perspective, contemplation" },
  { name: "Death", meaning: "transformation, endings, change, transition, letting go, release" },
  { name: "Temperance", meaning: "balance, peace, patience, moderation, calm, tranquillity, harmony, serenity" },
  { name: "The Devil", meaning: "oppression, addiction, obsession, dependency, excess, powerlessness, limitations" },
  { name: "The Tower", meaning: "disaster, destruction, upheaval, trauma, sudden change, chaos" },
  { name: "The Star", meaning: "hope, inspiration, positivity, faith, renewal, healing, rejuvenation" },
  { name: "The Moon", meaning: "illusion, intuition, uncertainty, confusion, complexity, secrets, unconscious" },
  { name: "The Sun", meaning: "happiness, success, optimism, vitality, joy, confidence, happiness, truth" },
  { name: "Judgement", meaning: "self-evaluation, awakening, renewal, purpose, reflection, reckoning" },
  { name: "The World", meaning: "completion, achievement, fulfilment, sense of belonging, wholeness, harmony" },

  { name: "Ace of Wands", meaning: "inspiration, creative spark, new initiative, new passion, enthusiasm, energy" },
  { name: "Two of Wands", meaning: "planning, first steps, making decisions, leaving comfort, taking risks" },
  { name: "Three of Wands", meaning: "momentum, confidence, expansion, growth, foresight, looking ahead" },
  { name: "Four of Wands", meaning: "community, home, celebrations, reunions, parties, gatherings, stability, belonging" },
  { name: "Five of Wands", meaning: "conflict, competition, arguments, aggression, tension, rivals, clashes of ego" },
  { name: "Six of Wands", meaning: "success, victory, triumph, rewards, recognition, praise, acclaim, pride" },
  { name: "Seven of Wands", meaning: "protectiveness, standing up for yourself, defending yourself, protecting territory" },
  { name: "Eight of Wands", meaning: "movement, speed, progress, quick decisions, sudden changes, excitement" },
  { name: "Nine of Wands", meaning: "last stand, persistence, grit, resilience, perseverance, close to success, fatigue" },
  { name: "Ten of Wands", meaning: "burden, responsibility, duty, stress, obligation, burning out, struggles" },
  { name: "Page of Wands", meaning: "adventure, excitement, fresh ideas, cheerfulness, energetic, fearless, extroverted" },
  { name: "Knight of Wands", meaning: "courageous, energetic, charming, hero, rebellious, hot tempered, free spirit" },
  { name: "Queen of Wands", meaning: "confident, self-assured, passionate, determined, social, charismatic, vivacious, optimistic" },
  { name: "King of Wands", meaning: "leadership, vision, big picture, taking control, daring decisions, boldness, optimism" },

  { name: "Ace of Cups", meaning: "love, new feelings, emotional awakening, creativity, spirituality, intuition" },
  { name: "Two of Cups", meaning: "unity, partnership, attraction, connection, close bonds, joining forces, mutual respec" },
  { name: "Three of Cups", meaning: "friendship, community, gatherings, celebrations, group events, social events" },
  { name: "Four of Cups", meaning: "apathy, contemplation, feeling disconnected, melancholy, boredom, indifference, discontent" },
  { name: "Five of Cups", meaning: "loss, grief, disappointment, sadness, mourning, discontent, feeling let down" },
  { name: "Six of Cups", meaning: "nostalgia, memories, familiarity, healing, comfort, sentimentality, pleasure" },
  { name: "Seven of Cups", meaning: "choices, searching for purpose, illusion, fantasy, daydreaming, wishful thinking, indecision" },
  { name: "Eight of Cups", meaning: "abandonment, walking away, letting go, searching for truth, leaving behind" },
  { name: "Nine of Cups", meaning: "wishes coming true, contentment, satisfaction, success, achievements, recognition, pleasure" },
  { name: "Ten of Cups", meaning: "happiness, homecomings, fulfillment, emotional stability, security, domestic harmony" },
  { name: "Page of Cups", meaning: "idealism, sensitivity, dreamer, naivete, innocence, inner child, head in the clouds" },
  { name: "Knight of Cups", meaning: "idealist, charming, artistic, graceful, tactful, diplomatic, mediator, negotiator" },
  { name: "Queen of Cups", meaning: "compassion, warmth, kindness, intuition, healer, counsellor, supportive" },
  { name: "King of Cups", meaning: "wise, diplomatic, balance between head and heart, devoted, advisor, counsellor" },

  { name: "Ace of Swords", meaning: "clarity, breakthrough, new idea, concentration, vision, force, focus, truth" },
  { name: "Two of Swords", meaning: "stalemate, difficult choices, stuck in the middle, denial, hidden information" },
  { name: "Three of Swords", meaning: "heartbreak, separation, sadness, grief, sorrow, upset, loss, trauma, tears" },
  { name: "Four of Swords", meaning: "rest, relaxation, peace, sanctuary, recuperation, self-protection, rejuvenation" },
  { name: "Five of Swords", meaning: "arguments, disputes, aggression, bullying, intimidation, conflict, hostility, stress" },
  { name: "Six of Swords", meaning: "moving on, departure, leaving behind, distance, accepting lessons" },
  { name: "Seven of Swords", meaning: "lies, trickery, scheming, strategy, resourcefulness,sneakiness, cunning" },
  { name: "Eight of Swords", meaning: "trapped, restricted, victimised, paralysed, helpless, powerless, imprisonment" },
  { name: "Nine of Swords", meaning: "fear, anxiety, negativity, breaking point, despair, nightmares, isolation" },
  { name: "Ten of Swords", meaning: "ruin, failure, bitterness, collapse, exhaustion, dead end, victimization, betrayal" },
  { name: "Page of Swords", meaning: "curious, witty, chatty, communicative, inspired, vigilant, alert, mental agility" },
  { name: "Knight of Swords", meaning: "assertive, direct, impatient, intellectual, daring, focused, perfectionist, ambitious" },
  { name: "Queen of Swords", meaning: "honest, independent, principled, fair, constructive criticism, objective, perceptive" },
  { name: "King of Swords", meaning: "reason, authority, discipline, integrity, morality, serious, high standards, strict" },

  { name: "Ace of Pentacles", meaning: "new opportunities, resources, abundance, prosperity, security, stability, manifestation" },
  { name: "Two of Pentacles", meaning: "balancing resources, adaptation, resourcefulness, flexibility, stretching resources" },
  { name: "Three of Pentacles", meaning: "teamwork, shared goals, collaboration, apprenticeship, effort, pooling energy" },
  { name: "Four of Pentacles", meaning: "possessiveness, insecurity, hoarding, stinginess, stability, security, savings, materialism, wealth, frugality, boundaries, guardedness" },
  { name: "Five of Pentacles", meaning: "hardship, loss, isolation, feeling abandoned, adversity, struggle, unemployment, alienation, disgrace" },
  { name: "Six of Pentacles", meaning: "generosity, charity, community, material help, support, sharing, giving and receiving, gratitude" },
  { name: "Seven of Pentacles", meaning: "harvest, rewards, results, growth, progress, perseverance, patience, planning" },
  { name: "Eight of Pentacles", meaning: "skill, talent, craftsmanship, quality, high standards, expertise, mastery, commitment, dedication, accomplishment" },
  { name: "Nine of Pentacles", meaning: "rewarded efforts, success, achievement, independence, leisure, material security, self-sufficiency" },
  { name: "Ten of Pentacles", meaning: "legacy, roots, family, ancestry, inheritance, windfall, foundations, privilege, affluence, stability, tradition" },
  { name: "Page of Pentacles", meaning: "ambitious, diligent, goal oriented, planner, consistent, star student, studious, grounded, loyal, faithful, dependable" },
  { name: "Knight of Pentacles", meaning: "practical, reliable, efficient, stoic, slow and steady, hard-working, committed, patient, conservative" },
  { name: "Queen of Pentacles", meaning: "generous, caring, nurturing, homebody, good business sense, practical, comforting, welcoming, sensible, luxurious" },
  { name: "King of Pentacles", meaning: "abundance, prosperity, security, ambitious, safe, kind, patriarchal, protective, businessman, provider, sensual, reliable" }
];
